DROP DATABASE IF EXISTS transporte_curitiba;
CREATE DATABASE transporte_curitiba;
USE transporte_curitiba;

CREATE TABLE usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL UNIQUE,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL
);

CREATE INDEX idx_email ON usuarios (email);
CREATE INDEX idx_cpf ON usuarios (cpf);

CREATE TABLE linhas_onibus (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome_linha VARCHAR(100) NOT NULL,
    codigo_linha VARCHAR(10) NOT NULL
);
 
INSERT INTO linhas_onibus (nome_linha, codigo_linha) VALUES
    ('A. MUNHOZ / JD. BOTÂNICO', '464'),
    ('ABAETÉ', '226'),
    ('ABRANCHES', '182'),
    ('ACRÓPOLE', '332'),
    ('AGRÍCOLA', '334'),
    ('ÁGUA VERDE', '863'),
    ('AHÚ / LOS ANGELES', '265'),
    ('ALFERES POLI', '560'),
    ('ALIANÇA', '232'),
    ('ALTO BOQUEIRÃO', '629'),
    ('ALTO TARUMÃ', '373'),
    ('ANITA GARIBALDI', '245'),
    ('ARAGUAIA', '311'),
    ('ATUBA / PINHEIRINHO', '350'),
    ('ATUBA/STA.CANDIDA', '238'),
    ('AUGUSTA', '823'),
    ('AUGUSTA/V. MARQUETO', '820'),
    ('AUGUSTO STRESSER', '361'),
    ('B. ALTO / ATUBA', '345'),
    ('B. ALTO / BOA VISTA', '342'),
    ('B. ALTO / STA. FELICIDADE', '307'),
    ('BAIRRO NOVO', '506'),
    ('BAIRRO NOVO A', '541'),
    ('BAIRRO NOVO B', '542'),
    ('BAIRRO NOVO B/C', '524'),
    ('BAIRRO NOVO C', '547'),
    ('BANESTADO / CALIFÓRNIA', '231'),
    ('BARIGUI', '862'),
    ('BARREIRINHA', '205'),
    ('BARREIRINHA / SÃO JOSÉ', '206'),
    ('BIGORRILHO', '875'),
    ('BOA VISTA / BARREIRINHA', '225'),
    ('BOM RETIRO / PUC', '175'),
    ('BOQUEIRÃO', '503'),
    ('BOQUEIRÃO / C. CÍVICO', '505'),
    ('BOQUEIRÃO/PINHEIRINHO', '528'),
    ('BOSCH', '627'),
    ('BRACATINGA', '170'),
    ('BRF / COPEL', 'X43'),
    ('BUTIATUVINHA', '913'),
    ('BUTIATUVINHA/ OURO VERDE', '948'),
    ('C. BELEM / S. FILHO', '516'),
    ('C. COMPRIDO / C. RASO', '828'),
    ('C. COMPRIDO / CIC', '826'),
    ('C. MÚSICA / V. ALEGRE', '150'),
    ('C. RASO / C. DO SIQUEIRA', '027'),
    ('C. RASO / CAIUÁ', '658'),
    ('C. RASO / CAMP. SIQUEIRA', '024'),
    ('CABRAL / OSÓRIO', '207'),
    ('CABRAL / PORTÃO', '216'),
    ('CABRAL / PQ.TANGUÁ', '177'),
    ('CABRAL/ESTAÇÃO PUC', '220'),
    ('CAIUÁ', '703'),
    ('CAIUA / C.COMPRIDO', '732'),
    ('CAIUA/CACHOEIRA', '702'),
    ('CAIUA/FAZ/CENTRO', '706'),
    ('CAJURU', '386'),
    ('CAMARGO', '322'),
    ('CAMP. SIQUEIRA / BATEL', '801'),
    ('CAMP. SIQUEIRA / STA.FELICIDADE', '816'),
    ('CAMPO ALEGRE', '654'),
    ('CANAL BELÉM', '475'),
    ('CARBOMAFRA', '628'),
    ('CASA DE CUSTÓDIA', '668'),
    ('CASSIOPÉIA', '224'),
    ('CAXIMBA / OLARIA', '659'),
    ('CENTENÁRIO', '305'),
    ('CENTENÁRIO / BOQUEIRÃO', '335'),
    ('CENTENÁRIO / C. COMPRIDO', '303'),
    ('CENTENÁRIO / HAUER', '338'),
    ('CENTENÁRIO / RUI BARBOSA', '302'),
    ('CENTRO POLITÉCNICO', '469'),
    ('CIC/CABRAL', '210'),
    ('CIRCULAR SUL (ANTI-HORÁRIO)', '602'),
    ('CIRCULAR SUL (HORÁRIO)', '502'),
    ('COLINA VERDE', '211'),
    ('COLOMBO / CIC', '607'),
    ('COMPLEXO INDUSTRIAL', '722'),
    ('COTOLENGO', '778'),
    ('CRISTO REI', '385'),
    ('DALAGASSA', '681'),
    ('DETRAN / VIC. MACHADO', '380'),
    ('DOM ÁTICO', '662'),
    ('E. VERÍSSIMO / PANTANAL', '533'),
    ('EMÍLIO ROMANI', '723'),
    ('ERASTO GAERTNER', '465'),
    ('ESPECIAL B.ALTO / C.IMBUIA', 'X45'),
    ('ESPECIAL BOQUEIRAO', 'X12'),
    ('ESTRIBO AHÚ', '266'),
    ('ESTUDANTES', '466'),
    ('F. NORONHA / LARANJEIRAS', '275'),
    ('FANNY', '621'),
    ('FAZENDINHA', '701'),
    ('FAZENDINHA / C. COMPRIDO', '720'),
    ('FAZENDINHA / C.RASO', '831'),
    ('FAZENDINHA / PORTÃO', '611'),
    ('FAZENDINHA / PUC', '614'),
    ('FAZENDINHA/CAIUÁ-B.VISTA', '724'),
    ('FERNÃO DIAS', '821'),
    ('FORMOSA', '673'),
    ('FUTURAMA', '639'),
    ('FUTURAMA / S. CERCADO', '683'),
    ('GABINETO', '822'),
    ('GANCHINHO', '642'),
    ('GRAMADOS', '625'),
    ('GUILHERMINA', '561'),
    ('HAUER / BOQUEIRÃO', '513'),
    ('HAUER / C.RASO', '525'),
    ('HIGIENÓPOLIS', '371'),
    ('HUGO LANGE', '374'),
    ('IGUAPE I', '523'),
    ('IGUAPE II', '515'),
    ('INTER 2 (ANTI-HORÁRIO)', '023'),
    ('INTER 2 (HORÁRIO)', '022'),
    ('INTERBAIRROS I (ANTI-HORÁRIO)', '011'),
    ('INTERBAIRROS I (HORÁRIO)', '010'),
    ('INTERBAIRROS II (ANTI-HORÁRIO)', '021'),
    ('INTERBAIRROS II (HORÁRIO)', '020'),
    ('INTERBAIRROS III', '030'),
    ('INTERBAIRROS IV', '040'),
    ('INTERBAIRROS V', '050'),
    ('INTERBAIRROS VI', '060'),
    ('ITAMARATI', '512'),
    ('ITATIAIA', '711'),
    ('ITUPAVA / HOSP. MILITAR', '366'),
    ('JD. CENTAURO', '468'),
    ('JD. CHAPARRAL', '183'),
    ('JD. DA ORDEM', '655'),
    ('JD. DO ARROIO', '244'),
    ('JD. ESPLANADA', '865'),
    ('JD. INDEPENDÊNCIA / CIC', '712'),
    ('JD. IPÊ', '917'),
    ('JD. ITÁLIA', '972'),
    ('JD. ITIBERÊ', '474'),
    ('JD. KOSMOS', '169'),
    ('JD. LUDOVICA', '617'),
    ('JD. MERCÊS / GUANABARA', '160'),
    ('JD. SOCIAL / BATEL', '365'),
    ('JD.PARANAENSE', '532'),
    ('JOSÉ CULPI', '912'),
    ('JÚLIO GRAF', '967'),
    ('LIGEIRÃO BOQUEIRÃO', '500'),
    ('LIGEIRÃO NORTE / SUL', '250'),
    ('LIGEIRÃO PINHEIRINHO / C. GOMES', '550'),
    ('LINDÓIA', '661'),
    ('LONDRINA', '635'),
    ('LUIZ NICHELE', '641'),
    ('MAD. ABRANCHES', '189'),
    ('MAD. BAIRRO NOVO', '549'),
    ('MAD. BOQUEIRÃO', '509'),
    ('MAD. CAIUÁ', '789'),
    ('MAD. CAMPO COMPRIDO', '809'),
    ('MAD. CENTENÁRIO', '309'),
    ('MAD. CENTENÁRIO / RUI BARBOSA', '308'),
    ('MAD. CIC', '609'),
    ('MAD. PENHA / F. NORONHA', '229'),
    ('MAD. PETRÓPOLIS / SOLITUDE', '489'),
    ('MAD. PILARZINHO / UBERABA', '188'),
    ('MAD. S. CÂNDIDA / C. RASO', '209'),
    ('MAD. S. FRANCISCO / IGUAPE', '519'),
    ('MAD. S. PEDRO / R. NEGRO', '689'),
    ('MAD. SÃO BRÁZ', '889'),
    ('MAD. STA. FELICIDADE', '989'),
    ('MAD. TARUMÃ / AUGUSTA', '389'),
    ('MAD. TATUQUARA', '679'),
    ('MAD. V. VELHA', '788'),
    ('MAL. HERMES / STA. EFIGÊNIA', '260'),
    ('MARIA ANGÉLICA', '633'),
    ('MARINGÁ', '522'),
    ('MÁRIO JORGE', '721'),
    ('MATEUS LEME', '181'),
    ('MERCÚRIO', '331'),
    ('MONTANA', '812'),
    ('MORADIAS PQ. IGUAÇU', '553'),
    ('MOSSUNGUÊ', '814'),
    ('NIVALDO BRAGA', '521'),
    ('NOVENA', '360'),
    ('NOVO MUNDO', '666'),
    ('NSA. SRA. DA LUZ', '674'),
    ('NSA.SRA.DE NAZARÉ', '280'),
    ('OLARIA', '233'),
    ('OSTERNACK / BOQUEIRÃO', '535'),
    ('OSTERNACK / S. CERCADO', '548'),
    ('OSTERNACK / S. CERCADO L.D.', '520'),
    ('OURO VERDE (VIA VL.BÁDIA)', '915'),
    ('PAINEIRAS', '272'),
    ('PALMEIRA', '640'),
    ('PALOTINOS', '387'),
    ('PARAÍSO', '343'),
    ('PARIGOT DE SOUZA', '534'),
    ('PARQUE ATUBA', '237'),
    ('PARQUE INDUSTRIAL', '623'),
    ('PARQUE NÁUTICO', '529'),
    ('PARQUE TANGUÁ', '176'),
    ('PASSAÚNA', '911'),
    ('PASSAÚNA / JD.IPÊ', '928'),
    ('PETRÓPOLIS', '462'),
    ('PINHAIS / C. COMPRIDO', '304'),
    ('PINHEIRINHO', '638'),
    ('PINHEIRINHO / CIC', '644'),
    ('PINHEIRINHO/CABRAL', '700'),
    ('PINHEIRINHO/RUI BARBOSA', '603'),
    ('PINHEIROS', '916'),
    ('PINHEIROS / JOSÉ CULPI', '958'),
    ('PIRATINI / BR-476', '631'),
    ('PIRINEUS', '649'),
    ('POMPEIA/JANAINA', '646'),
    ('PORTÃO', '671'),
    ('PORTÃO / CIC', '612'),
    ('PORTAO / STA.BERNADETHE', '616'),
    ('PORTAO/SITIO CERCADO', 'X20'),
    ('PORTO BELO', '718'),
    ('POSIVILLE / INC', '832'),
    ('PQ. LAGO AZUL', '794'),
    ('PRIMAVERA', '171'),
    ('PUC/RODOFERROVIARIA', '518'),
    ('QUARTEL GENERAL', '632'),
    ('RAPOSO TAVARES', '168'),
    ('REF. GUADALUPE / FAZENDINHA', 'X36'),
    ('REFORÇO PINHEIRINHO', 'X08'),
    ('REFORÇO SABARÁ', 'X41'),
    ('REFORÇO TUBO BARIGUI', 'X02'),
    ('REFORÇO TUIUTI', '815'),
    ('RIO BONITO', '684'),
    ('RIO BONITO / CIC', '685'),
    ('RIO BONITO (SEMI-DIRETO)', 'X38'),
    ('RIO NEGRO', '636'),
    ('RIVIERA', '827'),
    ('RONDON', '622'),
    ('R.PRADO/C.GOMES', '164'),
    ('RURBANA', '680'),
    ('S. CERCADO / C. RASO', '610'),
    ('SABARÁ', '653'),
    ('SAGRADO CORAÇÃO', '375'),
    ('SAMBAQUI', '552'),
    ('SÃO BENEDITO', '236'),
    ('SÃO BERNARDO', '965'),
    ('SÃO BRAZ', '870'),
    ('SÃO JOÃO', '213'),
    ('SÃO JORGE', '670'),
    ('SATURNO / VENEZA', '817'),
    ('SAVÓIA', '876'),
    ('SITIO CERCADO / C. RASO', 'X11'),
    ('SÍTIO CERCADO (ANTI-HORÁRIO)', '508'),
    ('SÍTIO CERCADO (HORÁRIO)', '507'),
    ('SOLAR', '212'),
    ('SOLITUDE', '463'),
    ('STA. AMÉLIA', '713'),
    ('STA. BARBARA', '461'),
    ('STA. CÂNDIDA / C. RASO', '203'),
    ('STA. CRUZ', '620'),
    ('STA. FELICIDADE', '901'),
    ('STA. FELICIDADE / PCA.TIRADENTES', '902'),
    ('STA. FELICIDADE / STA. CÂNDIDA', '924'),
    ('STA. GEMA', '274'),
    ('STA. INÊS', '531'),
    ('STA. JOANA', '637'),
    ('STA. QUITÉRIA', '760'),
    ('STA. RITA / CIC', '619'),
    ('STA. RITA / PINH. (SEMI DIRETO)', 'X37'),
    ('STA. RITA / PINHEIRINHO', '650'),
    ('STA. TEREZINHA', '243'),
    ('STA.AMELIA/P.BELO', '710'),
    ('TARUMÃ', '372'),
    ('TATUQUARA / CENTRO', '707'),
    ('TEQUALY', '864'),
    ('TEQUALY/QUARTEL GENERAL', '600'),
    ('TINGUI', '214'),
    ('TRABALHADOR', '545'),
    ('TRAMONTINA', '861'),
    ('TRINDADE', '321'),
    ('TUPY/JULIANA', '772'),
    ('TURISMO', '979'),
    ('UBERABA', '472'),
    ('UBERLÂNDIA', '615'),
    ('UMBARÁ', '643'),
    ('UNIV.POSITIVO', '829'),
    ('V. AUTÓDROMO', '323'),
    ('V. CUBAS', '663'),
    ('V. ESPERANÇA', '222'),
    ('V. IZABEL', '761'),
    ('V. JULIANA', '690'),
    ('V. LEONICE', '242'),
    ('V. MACEDO VIA GUABIROTUBA', '477'),
    ('V. MARQUETO', '825'),
    ('V. NORI', '166'),
    ('V. RENO', '336'),
    ('V. REX', '665'),
    ('V. ROSINHA', '762'),
    ('V. SANDRA', '860'),
    ('V. SÃO PAULO', '471'),
    ('V. SÃO PEDRO', '624'),
    ('V. SUIÇA', '184'),
    ('V. VELHA', '777'),
    ('V. VELHA/BURITI', '779'),
    ('V. VERDE', '652'),
    ('VITÓRIA RÉGIA', '630'),
    ('VIZINHANÇA/STA. RITA', '773'),
    ('ZOOLÓGICO', '536');
